name: Use Custom MySQL Client Action

on:  
  workflow_dispatch:

jobs:
  install-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install MySQL Client
      uses: suresh609/mysql-client-custom-action@v1

    - name: Verify MySQL Client Installation
      run: mysql --version
